import { City, Element, Weapon, Artifacts } from "./utils";

export const CHARACTER = {
  xueyi: {
    key: "Xueyi",
    id: "xueyi",
    name: "雪衣",
    prefix: Weapon.Destruction.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Quantum,
    weapon: Weapon.Destruction
  },
  dr_ratio: {
    key: "Dr Ratio",
    id: "dr_ratio",
    name: "真理医生",
    prefix: Weapon.Hunt.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Imaginary,
    weapon: Weapon.Hunt
  },
  ruan_mei: {
    key: "Ruan Mei",
    id: "ruan_mei",
    name: "阮·梅",
    prefix: Weapon.Harmony.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.HertaSpaceStation,
    ele: Element.Ice,
    weapon: Weapon.Harmony
  },
  hanya: {
    key: "Hanya",
    id: "hanya",
    name: "寒鸦",
    prefix: Weapon.Harmony.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Physical,
    weapon: Weapon.Harmony
  },
  argenti: {
    key: "Argenti",
    id: "argenti",
    name: "银枝",
    prefix: Weapon.Erudition.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Physical,
    weapon: Weapon.Erudition
  },
  huohuo: {
    key: "Huohuo",
    id: "huohuo",
    name: "藿藿",
    prefix: Weapon.Abundance.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Wind,
    weapon: Weapon.Abundance
  },
  guinaifen: {
    key: "Guinaifen",
    id: "guinaifen",
    name: "桂乃芬",
    prefix: Weapon.Nihility.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Fire,
    weapon: Weapon.Nihility
  },
  topaz_numby: {
    key: "Topaz & Numby",
    id: "topaz_numby",
    name: "托帕&账账",
    prefix: Weapon.Hunt.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Fire,
    weapon: Weapon.Hunt
  },
  jingliu: {
    key: "Jingliu",
    id: "jingliu",
    name: "镜流",
    prefix: Weapon.Destruction.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Ice,
    weapon: Weapon.Destruction
  },
  lynx: {
    key: "Lynx",
    id: "lynx",
    name: "玲可",
    prefix: Weapon.Abundance.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.JariloVI,
    ele: Element.Quantum,
    weapon: Weapon.Abundance
  },
  dan_heng_imbibitor_lunae: {
    key: 'Dan Heng · Imbibitor Lunae',
    id: "dan_heng_imbibitor_lunae",
    name: '丹恒•饮月',
    prefix: Weapon.Destruction.name,
    star: 5,
    event_exclusive: true,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Imaginary,
    weapon: Weapon.Destruction
  },
  luka: {
    key: "Luka",
    id: "luka",
    name: "卢卡",
    prefix: Weapon.Nihility.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.JariloVI,
    ele: Element.Physical,
    weapon: Weapon.Nihility
  },
  kafka: {
    key: "Kafka",
    id: "kafka",
    name: "卡芙卡",
    prefix: Weapon.Nihility.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.StellaronHunters,
    ele: Element.Lightning,
    weapon: Weapon.Nihility
  },
  blade: {
    key: "Blade",
    id: "blade",
    name: "刃",
    prefix: Weapon.Destruction.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.StellaronHunters,
    ele: Element.Wind,
    weapon: Weapon.Destruction
  },
  fu_xuan: {
    key: "Fu Xuan",
    id: "fu_xuan",
    name: "符玄",
    prefix: Weapon.Preservation.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.TheXianzhouLuofu,
    ele: Element.Quantum,
    weapon: Weapon.Preservation
  },
  seele: {
    key: "Seele",
    id: "seele",
    name: "希儿",
    prefix: Weapon.Hunt.name,
    star: 5,
    event_exclusive: true,
    intro: "",
    city: City.JariloVI,
    ele: Element.Quantum,
    weapon: Weapon.Hunt
  },
  hook: {
    key: "Hook",
    id: "hook",
    name: "虎克",
    prefix: Weapon.Destruction.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.JariloVI,
    ele: Element.Fire,
    weapon: Weapon.Destruction
  },
  pela: {
    key: "Pela",
    id: "pela",
    name: "佩拉",
    prefix: Weapon.Nihility.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.JariloVI,
    ele: Element.Ice,
    weapon: Weapon.Nihility
  },
  natasha: {
    key: "Natasha",
    id: "natasha",
    name: "娜塔莎",
    prefix: Weapon.Abundance.name,
    star: 4,
    event_exclusive: false,
    intro: "",
    city: City.JariloVI,
    ele: Element.Physical,
    weapon: Weapon.Abundance
  },
  yukong: {
    key: 'Yukong',
    id: "yukong",
    name: '驭空',
    prefix: Weapon.Harmony.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Imaginary,
    weapon: Weapon.Harmony
  },
  luocha: {
    key: 'Luocha',
    id: "luocha",
    name: '罗刹',
    prefix: Weapon.Abundance.name,
    star: 5,
    event_exclusive: true,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Imaginary,
    weapon: Weapon.Abundance
  },
  silver_wolf: {
    key: 'Silver Wolf',
    id: "silver_wolf",
    name: '银狼',
    prefix: Weapon.Nihility.name,
    star: 5,
    event_exclusive: true,
    intro: '',
    city: City.StellaronHunters,
    ele: Element.Quantum,
    weapon: Weapon.Nihility
  },
  bailu: {
    key: 'Bailu',
    id: "bailu",
    name: '白露',
    prefix: Weapon.Abundance.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Lightning,
    weapon: Weapon.Abundance
  },
  yanqing: {
    key: 'Yanqing',
    id: "yanqing",
    name: '彦卿',
    prefix: Weapon.Hunt.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Ice,
    weapon: Weapon.Hunt
  },
  sushang: {
    key: 'Sushang',
    id: "sushang",
    name: '素裳',
    prefix: Weapon.Hunt.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Physical,
    weapon: Weapon.Hunt
  },
  jing_yuan: {
    key: 'Jing Yuan',
    id: "jing_yuan",
    name: '景元',
    prefix: Weapon.Erudition.name,
    star: 5,
    event_exclusive: true,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Lightning,
    weapon: Weapon.Erudition
  },
  tingyun: {
    key: 'Tingyun',
    id: "tingyun",
    name: '停云',
    prefix: Weapon.Harmony.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Lightning,
    weapon: Weapon.Harmony
  },
  qingque: {
    key: 'Qingque',
    id: "qingque",
    name: '青雀',
    prefix: Weapon.Erudition.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.TheXianzhouLuofu,
    ele: Element.Quantum,
    weapon: Weapon.Erudition
  },
  sampo: {
    key: 'Sampo',
    id: "sampo",
    name: '桑博',
    prefix: Weapon.Nihility.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.JariloVI,
    ele: Element.Wind,
    weapon: Weapon.Nihility
  },
  clara: {
    key: 'Clara',
    id: "clara",
    name: '克拉拉',
    prefix: Weapon.Destruction.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.JariloVI,
    ele: Element.Physical,
    weapon: Weapon.Destruction
  },
  gepard: {
    key: 'Gepard',
    id: "gepard",
    name: '杰帕德',
    prefix: Weapon.Preservation.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.JariloVI,
    ele: Element.Ice,
    weapon: Weapon.Preservation
  },
  serval: {
    key: 'Serval',
    id: "serval",
    name: '希露瓦',
    prefix: Weapon.Erudition.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.JariloVI,
    ele: Element.Lightning,
    weapon: Weapon.Erudition
  },
  bronya: {
    key: 'Bronya',
    id: "bronya",
    name: '布洛妮娅',
    prefix: Weapon.Harmony.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.JariloVI,
    ele: Element.Wind,
    weapon: Weapon.Harmony
  },
  herta: {
    key: 'Herta',
    id: "herta",
    name: '黑塔',
    prefix: Weapon.Erudition.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.HertaSpaceStation,
    ele: Element.Ice,
    weapon: Weapon.Erudition
  },
  asta: {
    key: 'Asta',
    id: "asta",
    name: '艾丝妲',
    prefix: Weapon.Harmony.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.HertaSpaceStation,
    ele: Element.Fire,
    weapon: Weapon.Harmony
  },
  arlan: {
    key: 'Arlan',
    id: "arlan",
    name: '阿兰',
    prefix: Weapon.Destruction.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.HertaSpaceStation,
    ele: Element.Lightning,
    weapon: Weapon.Destruction
  },
  welt: {
    key: 'Welt',
    id: "welt",
    name: '瓦尔特',
    prefix: Weapon.Nihility.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.AstralExpress,
    ele: Element.Imaginary,
    weapon: Weapon.Nihility
  },
  himeko: {
    key: 'Himeko',
    id: "himeko",
    name: '姬子',
    prefix: Weapon.Erudition.name,
    star: 5,
    event_exclusive: false,
    intro: '',
    city: City.AstralExpress,
    ele: Element.Fire,
    weapon: Weapon.Erudition
  },
  dan_heng: {
    key: 'Dan Heng',
    id: "dan_heng",
    name: '丹恒',
    prefix: Weapon.Hunt.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.AstralExpress,
    ele: Element.Wind,
    weapon: Weapon.Hunt
  },
  march_7th: {
    key: 'March 7th',
    id: "march_7th",
    name: '三月七',
    prefix: Weapon.Preservation.name,
    star: 4,
    event_exclusive: false,
    intro: '',
    city: City.AstralExpress,
    ele: Element.Ice,
    weapon: Weapon.Preservation
  },
}
