pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot/Renovate/Requires.io pull requests
    conditions:
      - or:
          - and:
              - author=dependabot[bot]
          - and:
              - title~=^\[requires.io\]
              - head~=^requires-io
          - and:
              - author=renovate[bot]
      # PR is not a draft
      - -draft
      # condition
      # https://docs.mergify.com/conditions/#github-actions
      # 不一定全都会响应 在此判定 任意一个失败都不可以，但是失败也不行，可能有 pending 之类的
      # 必须用 not or
      # 修改成这样是因为 无法匹配 matrix
      # https://github.com/Mergifyio/mergify/discussions/5067#discussioncomment-4859692
      # need to list every CI that you expect.
      # https://github.com/Mergifyio/mergify/discussions/5119
      # https://github.com/Mergifyio/mergify/discussions/5120
      - or:
          # workflows
          - files~=^.github/workflows/
          # deploy
          - files~=^life/
          - files~=^game/
          - files=package.json
          - files=pnpm-lock.yaml
          # py
          - files~=^script/
      # deploy life
      - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      # deploy game
      - -check-failure=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
      - -check-neutral=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
      - -check-pending=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
      # py-life-recent
      - -check-failure=py-life-recent
      - -check-neutral=py-life-recent
      - -check-pending=py-life-recent
      # py-game-wish
      - -check-failure=py-game-wish
      - -check-neutral=py-game-wish
      - -check-pending=py-game-wish
    actions:
      merge:
        method: merge

  - name: automatic merge for python script latest life
    conditions:
      - author=DrAugus
      - "title=docs: life latest"
      # deploy life
      - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
      - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
    actions:
      merge:
        method: merge

  # - name: automatic merge for auto get mhy wish
  #   conditions:
  #     - author=DrAugus
  #     - "title=feat: auto get mhy wish"
  #     - check-success~=^deploy-
  #     - -check-failure~=^py-
  #   actions:
  #     merge:
  #       method: merge

  # - name: automatic merge for dev-game/py
  #   conditions:
  #     - author=DrAugus
  #     - or:
  #       - head=dev-game
  #       - head=dev-py
  #     # PR is not a draft
  #     - -draft
  #     - or:
  #       # deploy
  #       - files~=^life/
  #       - files~=^game/
  #       - files=".github/workflows/deploy-life.yml"
  #       - files=".github/workflows/deploy-game.yml"
  #       - files=pnpm-lock.yaml
  #       # py
  #       - files="script/requirements.txt"
  #       - files=".github/workflows/get-mhy-wish.yml"
  #       - files=".github/workflows/life-recent-update.yml"
  #       - files~=^script/mihoyo
  #       - files="script/miyoushe.py"
  #       - files="script/hoyolab.py"
  #     # deploy life
  #     - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
  #     - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
  #     - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, life)
  #     - -check-failure=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
  #     - -check-neutral=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
  #     - -check-pending=deploy-life (ubuntu-latest, life/.vitepress/dist, augusmeow, augusmeow.github.io)
  #     # deploy game
  #     - -check-failure=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
  #     - -check-neutral=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
  #     - -check-pending=deploy-game (ubuntu-latest, game/.vitepress/dist, augusmeow, game)
  #     # py-life-recent
  #     - -check-failure=py-life-recent
  #     - -check-neutral=py-life-recent
  #     - -check-pending=py-life-recent
  #     # py-game-wish
  #     - -check-failure=py-game-wish
  #     - -check-neutral=py-game-wish
  #     - -check-pending=py-game-wish
  #   actions:
  #     merge:
  #       method: merge

  # https://docs.mergify.com/workflow/delete-head-branches/#prevent-deletion-for-dependent-branches
  - name: delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
