export const sidebar = {
    '/eat/': [
        {
            text: '吃点儿',
            collapsible: true,
            items: [
                { text: '真的不能吃', link: '/eat/block' },
                { text: '做点什么吧', link: '/eat/cookbook' },
                { text: '吃饭了', link: '/eat/choose' },
            ],
        }
    ],
    '/trip/': [
        { text: '规划指南', link: '/trip/' },
        { text: '探索', link: '/trip/explore' },
        { text: '护照和签证的区别', link: '/trip/passport-vs-visa' },
        { text: '境外卡办理指南', link: '/trip/card' },
        { text: '签证', link: '/trip/visa' },
        { text: '护照', link: '/trip/passport' },
    ],
    '/trip/china/': [
        { text: '上海', link: '/trip/china/shanghai' },
        { text: '开封', link: '/trip/china/henan/kaifeng' },
        { text: '郑州', link: '/trip/china/henan/zhengzhou' },
        { text: '洛阳', link: '/trip/china/henan/luoyang' },
        { text: '河南', link: '/trip/china/henan/' },
        { text: '福州', link: '/trip/china/fujian/fuzhou' },
        { text: '福建', link: '/trip/china/fujian/' },
        { text: '厦门', link: '/trip/china/fujian/xiamen' },
        { text: '大理', link: '/trip/china/yunnan/dali' },
        { text: '西双版纳', link: '/trip/china/yunnan/xishuangbanna' },
        { text: '昆明', link: '/trip/china/yunnan/kunming' },
        { text: '云南', link: '/trip/china/yunnan/' },
        { text: '丽江', link: '/trip/china/yunnan/lijiang' },
        { text: '湖北', link: '/trip/china/hubei/' },
        { text: '武汉', link: '/trip/china/hubei/wuhan' },
        { text: '柳州', link: '/trip/china/guangxi/liuzhou' },
        { text: '广西', link: '/trip/china/guangxi/' },
        { text: '南宁', link: '/trip/china/guangxi/nanning' },
        { text: '成都', link: '/trip/china/sichuan/chengdu' },
        { text: '四川', link: '/trip/china/sichuan/' },
        { text: '贵州', link: '/trip/china/guizhou/' },
        { text: '贵阳', link: '/trip/china/guizhou/guiyang' },
        { text: '澳门', link: '/trip/china/macao' },
        { text: '深圳', link: '/trip/china/guangdong/shenzhen' },
        { text: '广东', link: '/trip/china/guangdong/' },
        { text: '广州', link: '/trip/china/guangdong/guangzhou' },
        { text: '中国', link: '/trip/china/' },
        { text: '长沙', link: '/trip/china/hunan/changsha' },
        { text: '湖南', link: '/trip/china/hunan/' },
        { text: '北京', link: '/trip/china/beijing' },
        { text: '苏州', link: '/trip/china/jiangsu/suzhou' },
        { text: '扬州', link: '/trip/china/jiangsu/yangzhou' },
        { text: '江苏', link: '/trip/china/jiangsu/' },
        { text: '南京', link: '/trip/china/jiangsu/nanjing' },
        { text: '无锡', link: '/trip/china/jiangsu/wuxi' },
        { text: '香港', link: '/trip/china/hongkong' },
        { text: '绍兴', link: '/trip/china/zhejiang/shaoxing' },
        { text: '浙江', link: '/trip/china/zhejiang/' },
        { text: '温州', link: '/trip/china/zhejiang/wenzhou' },
        { text: '杭州', link: '/trip/china/zhejiang/hangzhou' },
        { text: '天津', link: '/trip/china/tianjin' },
        { text: '重庆', link: '/trip/china/chongqing' },
    ],
    '/trip/abroad': [
        { text: '世界', link: '/trip/abroad/' },
        {
            text: '欧洲',
            collapsible: true,
            items: [
                { text: '英国', link: '/trip/abroad/europe/england' },
            ],
        },
        {
            text: '亚洲',
            collapsible: true,
            items: [
                { text: '韩国', link: '/trip/abroad/asia/korean' },
                { text: '日本', link: '/trip/abroad/asia/japan' },
            ],
        },
    ],
}