export const sidebar_zh = {

    '/genshin/': [
        { text: '米哈游 cookie', link: "/genshin/mihoyo-cookie" },
        { text: '近期祈愿', link: "/genshin/wish-recent" },
        { text: '祈愿时间轴', link: "/genshin/timeline" },
        { text: '祈愿信息汇总(带图)', link: "/genshin/wish-all" },
        { text: '祈愿信息汇总', link: "/genshin/wish-all2" },
        { text: '角色列表', link: "/genshin/character" },
        { text: '复刻祈愿', link: "/genshin/fork" },
        { text: 'up 次数统计', link: "/genshin/uptimes" },
        { text: 'up 次数表格统计', link: "/genshin/uptable" },
        { text: '提瓦特通用文字', link: "/genshin/language" },
        { text: '多少天可以满级', link: "/genshin/level" },
        { text: '队伍推荐', link: "/genshin/party" },
        { text: '圣遗物', link: "/genshin/artifacts" },
        { text: '有趣的台词', link: "/genshin/dialog" },
        { text: '怪物语音', link: "/genshin/monster" },
    ],

    '/hsr/': [
        { text: '近期跃迁', link: "/hsr/wish-recent" },
        { text: '跃迁时间轴', link: "/hsr/timeline" },
        { text: '跃迁信息汇总(带图)', link: "/hsr/wish-all" },
        { text: '跃迁信息汇总', link: "/hsr/wish-all2" },
        { text: '角色列表', link: "/hsr/character" },
        { text: '模拟宇宙', link: "/hsr/simulated-universe" },
        // { text: '复刻跃迁', link: "/hsr/fork" },
        // { text: 'up 次数统计', link: "/hsr/uptimes" },
        // { text: 'up 次数表格统计', link: "/hsr/uptable" },
        // { text: '提瓦特通用文字', link: "/hsr/language" },
        // { text: '多少天可以满级', link: "/hsr/level" },
        // { text: '队伍推荐', link: "/hsr/party" },
        { text: '遗器', link: "/hsr/relics" },
        // { text: '有趣的台词', link: "/hsr/dialog" },
        // { text: '怪物语音', link: "/hsr/monster" },
    ],
}