export const sidebar = {
    '/article/': [
        {
            text: '文章',
            collapsible: true,
            items: [
                { text: 'todo', link: '/article/' },
                { text: '猫', link: '/article/猫' },
                { text: '庄子·秋水', link: '/article/庄子·秋水' },
                { text: '道德经', link: '/article/道德经' },
                { text: '逍遥游·北冥有鱼', link: '/article/逍遥游·北冥有鱼' },
                { text: '聪明人和傻子和奴才', link: '/article/聪明人和傻子和奴才' },
            ],
        }
    ],
    '/xiwen/': [
        {
            text: '檄文',
            collapsible: true,
            items: [
                { text: 'about', link: '/xiwen/' },
                { text: '汤誓', link: '/xiwen/汤誓' },
                { text: '牧誓', link: '/xiwen/牧誓' },
                { text: '甘誓', link: '/xiwen/甘誓' },
                { text: '费誓', link: '/xiwen/费誓' },
                { text: '檄蜀文', link: '/xiwen/檄蜀文' },
                { text: '兴师檄文', link: '/xiwen/兴师檄文' },
                { text: '吕相绝秦', link: '/xiwen/吕相绝秦' },
                { text: '檄告楚相', link: '/xiwen/檄告楚相' },
                { text: '白朗告示', link: '/xiwen/白朗告示' },
                { text: '讨王莽檄', link: '/xiwen/讨王莽檄' },
                { text: '讨粤匪檄', link: '/xiwen/讨粤匪檄' },
                { text: '谕巴蜀檄', link: '/xiwen/谕巴蜀檄' },
                { text: '剿兵安民檄', link: '/xiwen/剿兵安民檄' },
                { text: '奉天讨胡檄', link: '/xiwen/奉天讨胡檄' },
                { text: '张献忠之檄', link: '/xiwen/张献忠之檄' },
                { text: '管仲檄楚使', link: '/xiwen/管仲檄楚使' },
                { text: '为袁绍檄豫州', link: '/xiwen/为袁绍檄豫州' },
                { text: '延平民人告白', link: '/xiwen/延平民人告白' },
                { text: '普告同胞檄稿', link: '/xiwen/普告同胞檄稿' },
                { text: '檄吴将校部曲', link: '/xiwen/檄吴将校部曲' },
                { text: '谕黑旗将士檄', link: '/xiwen/谕黑旗将士檄' },
                { text: '钦赐督辅手敕', link: '/xiwen/钦赐督辅手敕' },
                { text: '隋文帝伐陈檄', link: '/xiwen/隋文帝伐陈檄' },
                { text: '为李密檄洛州文', link: '/xiwen/为李密檄洛州文' },
                { text: '宁波众义民公启', link: '/xiwen/宁波众义民公启' },
                { text: '朱元璋北伐檄文', link: '/xiwen/朱元璋北伐檄文' },
                { text: '第二次讨袁宣言', link: '/xiwen/第二次讨袁宣言' },
                { text: '郑畋传檄天下文', link: '/xiwen/郑畋传檄天下文' },
                { text: '为徐敬业讨武曌檄', link: '/xiwen/为徐敬业讨武曌檄' },
                { text: '为窦建德檄秦王文', link: '/xiwen/为窦建德檄秦王文' },
                { text: '台湾人民抗战檄文', link: '/xiwen/台湾人民抗战檄文' },
                { text: '吴王刘濞遗诸侯书', link: '/xiwen/吴王刘濞遗诸侯书' },
                { text: '扑灭异端邪教公启', link: '/xiwen/扑灭异端邪教公启' },
                { text: '李自成檄明臣庶文', link: '/xiwen/李自成檄明臣庶文' },
                { text: '杨复光露布献捷文', link: '/xiwen/杨复光露布献捷文' },
                { text: '中华民国军起义檄文', link: '/xiwen/中华民国军起义檄文' },
                { text: '中国革命军大元帅檄', link: '/xiwen/中国革命军大元帅檄' },
                { text: '移河南郡县讨刘豫檄', link: '/xiwen/移河南郡县讨刘豫檄' },
                { text: '三元里等乡痛骂鬼子词', link: '/xiwen/三元里等乡痛骂鬼子词' },
                { text: '大顺军传牌山西各郡县', link: '/xiwen/大顺军传牌山西各郡县' },
                { text: '就陆海军大元帅职宣言', link: '/xiwen/就陆海军大元帅职宣言' },
                { text: '捻军盟主张乐行的布告', link: '/xiwen/捻军盟主张乐行的布告' },
                { text: '中华民国讨逆军檄告天下', link: '/xiwen/中华民国讨逆军檄告天下' },
                { text: '为李密檄荥阳守郇王庆文', link: '/xiwen/为李密檄荥阳守郇王庆文' },
                { text: '杨玄感敦促樊子盖归义书', link: '/xiwen/杨玄感敦促樊子盖归义书' },
                { text: '大清国摄政王多尔衮南下告示', link: '/xiwen/大清国摄政王多尔衮南下告示' },
                { text: '宣谕云、贵文武官员军民人等诏', link: '/xiwen/宣谕云、贵文武官员军民人等诏' },
                { text: '尽忠报国全粤义民申谕英夷告示', link: '/xiwen/尽忠报国全粤义民申谕英夷告示' },
                { text: '谕南京等处文武官员军民人等告示', link: '/xiwen/谕南京等处文武官员军民人等告示' },
            ]
        },
    ]
}